_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_pose_resnet_backbone
    DEPTH: 101x
    # WITH_IBN: False
    # WITH_NL : False
  META_ARCHITECTURE: PoseBaseline

# DATASETS:
#   NAMES: ("Market1501",)
#   TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/sbs-R101-ibn-debug0512-ep90-test-on-duke

INPUT:
  SIZE_TRAIN: [ 256, 192 ]
  SIZE_TEST: [ 256, 192 ]

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("DukeMTMC",)
  POSE: true
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  AMP:
    ENABLED: true
  MAX_EPOCH: 90
  # ETA_MIN_LR: 5e-07
  # BASE_LR: 0.0007
  # WARMUP_ITERS: 2000

TEST:
  IMS_PER_BATCH: 64