_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_pose_resnet_backbone
    DEPTH: 101x
    WITH_IBN: True
  META_ARCHITECTURE: PoseBaseline


OUTPUT_DIR: logs/market1501/sbs_R18-ibn-256-192-resnet101-vis-new-lup-unfreeze_posnet-new_freezing20ep-ep120


INPUT:
  SIZE_TRAIN: [ 256, 192 ]
  SIZE_TEST: [ 256, 192 ]

DATASETS:
  NAMES: ("OccludedDukeMTMC",)
  TESTS: ("OccludedDukeMTMC",)
  POSE: true
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  AMP:
    ENABLED: true
  MAX_EPOCH: 120
  # MAX_EPOCH: 160
  # BASE_LR: 0.00060
  # WARMUP_ITERS: 3500

TEST:
  IMS_PER_BATCH: 64