_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_pose_resnet_backbone
    DEPTH: 101x
    WITH_IBN: True
  META_ARCHITECTURE: PoseBaseline

# DATASETS:
#   NAMES: ("Market1501",)
#   TESTS: ("Market1501",)

OUTPUT_DIR: logs/msmt17/sbs_R18-ibn-256-192-resnet101-vis-new-lup-unfreeze_posnet-new_freezing20ep-ep120


INPUT:
  SIZE_TRAIN: [ 256, 192 ]
  SIZE_TEST: [ 256, 192 ]

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)
  POSE: true
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  AMP:
    ENABLED: true
  MAX_EPOCH: 120
  # BASE_LR: 0.00075
  # WARMUP_ITERS: 2000

TEST:
  IMS_PER_BATCH: 64